name: Simple CI

env:
  VAR_INT: "variable interne"
  
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: TEST

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Release
        uses: ncipollo/release-action@v1.14.0

      - name: Run an online script
        run: echo "hello world"

      - name: Deploy to server
        env:
          DEPLOY_KEY: ${{ secrets.MA_SECRET }}
        run: |
          echo "VAR = ${{ vars.MA_VAR }} Secret = $DEPLOY_KEY ${{ github.ref }} ${{ github.actor }} $VAR_INT"
    
        
