name: Simple CI

env:
  VAR_INT: "variable interne"
  
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment: TEST

    strategy:
      matrix:
        node-version: [12, 14]
    
    if: github.event_name == 'push'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: 
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install
        
      - uses: actions/github-script@v7
        id: set-result
        with:
         script: return "Hello!"
         result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"

      - name: Run an online script
        run: echo "hello world"

      - name: Deploy to server
        env:
          DEPLOY_KEY: ${{ secrets.MA_SECRET }}
        run: |
          echo "VAR = ${{ vars.MA_VAR }} Secret = $DEPLOY_KEY ${{ github.ref }} ${{ github.actor }} $VAR_INT"
    
        
